/*
 * Copyright (c) 2019-present Sonatype, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Base Error type for any Error generated by our Extension code.
 */
export class ExtensionError extends Error {
    constructor(messsage: string) {
        super(messsage)
    }
}

/**
 * Error thrown when configuration of the extension is invalid.
 *
 * For example - attempting to access IQ configuration when data source is set to OSS INDEX.
 */
export class InvalidConfigurationError extends ExtensionError {}
